class TestMemberListResponse:
    TEST_MEMBER_LIST = [
        {
            "login": "felix",
            "id": 4426,
            "node_id": "MDQ6VXNlcjQ0MjY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/4426?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/felix",
            "html_url": "https://github.com/felix",
            "followers_url": "https://api.github.com/users/felix/followers",
            "following_url": "https://api.github.com/users/felix/following{/other_user}",
            "gists_url": "https://api.github.com/users/felix/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/felix/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/felix/subscriptions",
            "organizations_url": "https://api.github.com/users/felix/orgs",
            "repos_url": "https://api.github.com/users/felix/repos",
            "events_url": "https://api.github.com/users/felix/events{/privacy}",
            "received_events_url": "https://api.github.com/users/felix/received_events",
            "type": "User",
            "site_admin": False,
        },
        {
            "login": "jcouyang",
            "id": 1235045,
            "node_id": "MDQ6VXNlcjEyMzUwNDU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1235045?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jcouyang",
            "html_url": "https://github.com/jcouyang",
            "followers_url": "https://api.github.com/users/jcouyang/followers",
            "following_url": "https://api.github.com/users/jcouyang/following{/other_user}",
            "gists_url": "https://api.github.com/users/jcouyang/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jcouyang/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jcouyang/subscriptions",
            "organizations_url": "https://api.github.com/users/jcouyang/orgs",
            "repos_url": "https://api.github.com/users/jcouyang/repos",
            "events_url": "https://api.github.com/users/jcouyang/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jcouyang/received_events",
            "type": "User",
            "site_admin": False,
        },
        {
            "login": "kpse",
            "id": 790027,
            "node_id": "MDQ6VXNlcjc5MDAyNw==",
            "avatar_url": "https://avatars.githubusercontent.com/u/790027?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/kpse",
            "html_url": "https://github.com/kpse",
            "followers_url": "https://api.github.com/users/kpse/followers",
            "following_url": "https://api.github.com/users/kpse/following{/other_user}",
            "gists_url": "https://api.github.com/users/kpse/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/kpse/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/kpse/subscriptions",
            "organizations_url": "https://api.github.com/users/kpse/orgs",
            "repos_url": "https://api.github.com/users/kpse/repos",
            "events_url": "https://api.github.com/users/kpse/events{/privacy}",
            "received_events_url": "https://api.github.com/users/kpse/received_events",
            "type": "User",
            "site_admin": False,
        },
        {
            "login": "RussVanBert",
            "id": 1724585,
            "node_id": "MDQ6VXNlcjE3MjQ1ODU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1724585?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/RussVanBert",
            "html_url": "https://github.com/RussVanBert",
            "followers_url": "https://api.github.com/users/RussVanBert/followers",
            "following_url": "https://api.github.com/users/RussVanBert/following{/other_user}",
            "gists_url": "https://api.github.com/users/RussVanBert/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/RussVanBert/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/RussVanBert/subscriptions",
            "organizations_url": "https://api.github.com/users/RussVanBert/orgs",
            "repos_url": "https://api.github.com/users/RussVanBert/repos",
            "events_url": "https://api.github.com/users/RussVanBert/events{/privacy}",
            "received_events_url": "https://api.github.com/users/RussVanBert/received_events",
            "type": "User",
            "site_admin": False,
        },
        {
            "login": "sudindinesh",
            "id": 11731882,
            "node_id": "MDQ6VXNlcjExNzMxODgy",
            "avatar_url": "https://avatars.githubusercontent.com/u/11731882?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/sudindinesh",
            "html_url": "https://github.com/sudindinesh",
            "followers_url": "https://api.github.com/users/sudindinesh/followers",
            "following_url": "https://api.github.com/users/sudindinesh/following{/other_user}",
            "gists_url": "https://api.github.com/users/sudindinesh/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/sudindinesh/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/sudindinesh/subscriptions",
            "organizations_url": "https://api.github.com/users/sudindinesh/orgs",
            "repos_url": "https://api.github.com/users/sudindinesh/repos",
            "events_url": "https://api.github.com/users/sudindinesh/events{/privacy}",
            "received_events_url": "https://api.github.com/users/sudindinesh/received_events",
            "type": "User",
            "site_admin": False,
        },
    ]
